# Generated by Django 3.0.7 on 2021-07-19 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepageslider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_text', models.CharField(max_length=1245)),
                ('slider_image', models.ImageField(upload_to='slider')),
                ('offer_text', models.CharField(max_length=45660)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('desc', models.TextField(max_length=1245)),
                ('sku', models.CharField(max_length=124)),
                ('prod_images', models.ImageField(upload_to='upload/')),
                ('price', models.IntegerField(default=25, max_length=1234)),
                ('is_featured', models.BooleanField(choices=[('yes', True), ('no', False)], default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('order_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eshop.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
